### ISSUE TITLE
Problem with unit Thread, with the function "CheckSynchronize", in Delphi 7.

### ISSUE THREAD

**Issue by ricardodelphi** [alexmerkel/mathparser#1]
When trying to compile in Delphi 7, there is a problem with the unit Thread, with the function "CheckSynchronize". The TInterlocked class has not been identified.

Original error message:
[Error] Thread.pas (115): Undeclared identifier: 'TInterlocked'

**Comment by alexmerkel** [comment]
Hi Ricardo,

thanks for raising the issue. Unfortunately I changed jobs recently. Therefore I currently don't have access to any version of Delphi.
So I won't be much help in solving this problem, but I'm always happy to accept a pull request.

Cheers,
Alex

**Comment by ricardojr01** [comment]
Hi Alex,

I'm Ricardo and I'm using my personal account. I made changes so that the source code compiles in delphi 7, as you said you are happy to accept a pull, I believe I have not hindered other aspects because I worked with the directives. I'm sorry for any spelling mistakes, English is not my native language.

Cheers,
Ricardo
